INDEXING: ACCESSING ARRAY ELEMENTS

In [4]:
import numpy as np

In [7]:
!pip install numpy

In [10]:
arr=np.array(range(10,21),np.int8)
print(arr)
print(arr[5])
print(arr[-2])
#Traverse array by index
for i in range(len(arr)):
    print(arr[i],end=" ")
print()
for item in arr:
    print(item,end=" ")
print()    
#Travers array by item index    

[10 11 12 13 14 15 16 17 18 19 20]
15
19
10 11 12 13 14 15 16 17 18 19 20 
10 11 12 13 14 15 16 17 18 19 20 


In [11]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]],np.int8)
print(arr)
print(arr[0,1])
print(arr[1][2])

[[1 2 3]
 [4 5 6]]
2
6


In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]],np.int8)
print(arr)
print(arr[0,1])
print(arr[1][2])

[[1 2 3]
 [4 5 6]]
2
6


In [ ]:
import numpy as np
arr=np.array([12,34,56,78,3,5,2,7,8,9,11,10,15])
print(arr)
print(arr[3:10])

In [5]:
#slicing 2d
arr2=np.array([[4,8,12,1,3],[6,8,11,2,6],[-1,6,7,8,9],[2,7,8,1,7]])
print(arr2)
#1.matrix of row1 and row2 2.matrix of col2 and col3
print(arr2[1:3,2:4])
print(arr2[-2:-1,-4:-2])

[[ 4  8 12  1  3]
 [ 6  8 11  2  6]
 [-1  6  7  8  9]
 [ 2  7  8  1  7]]
[[11  2]
 [ 7  8]]
[[6 7]]


In [6]:
import numpy as np
arr3=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])
print(arr3)
print(arr3[1:3,1:3,1:])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
[[[10]
  [12]]

 [[16]
  [18]]]


In [7]:
arr1=np.array([12,13,14,15,16,17,18,19,20,21,22,23])
print(arr1)
b=arr1[4:8]
print(b)
b[2]=100
print(b) #view
print(arr1)

[12 13 14 15 16 17 18 19 20 21 22 23]
[16 17 18 19]
[ 16  17 100  19]
[ 12  13  14  15  16  17 100  19  20  21  22  23]


RESHAPE>>>.FOR more than 2or 3 dimension number


In [24]:
import numpy as np
a=np.arange(15)
print(a)
a2=a.reshape(3,5)
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


RESIZE

In [19]:
arr=np.arange(12)
print(arr)
arr.resize(3,2)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[0 1]
 [2 3]
 [4 5]]


In [34]:
#USING ZEROS MATRIX
a=np.zeros((3,5),dtype=np.int32)
print(a)
print(a.dtype)

#USING ONSE MATRIX
a=np.ones((2,5,2),dtype=np.int32)
print(a)

#IDENTITY MATRIX
a=np.identity(3)
print(a)
#USING EYE() MATRIX
a=np.eye(3,4)
print(a)
#USING LINESPACE() FUNCTION
a=np.linspace(1,5,6)
print(a)

#USING RAVEL() METHOD  yee 3 or2 dimentional arrey ko 1 dimention array me bedal de ta hai
a=np.arange(12).reshape(3,4)
print(a)
a2=np.ravel(a)
print(a2)
a2[4]=200
print(a)
print(a2)

##
a=np.random.randint(2,10,size=(3,5,4))
print(a)



[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
int32
[[[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[1.  1.8 2.6 3.4 4.2 5. ]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[  0   1   2   3]
 [200   5   6   7]
 [  8   9  10  11]]
[  0   1   2   3 200   5   6   7   8   9  10  11]


REPLICATION,JOINING,EXISTING ARRAYS

In [42]:
a=np.arange(5,17).reshape((3,4))
print(a)
b=a[2:,1:3]
print(b)
b[0][1]=200
print(b)
print(a)
##################
a=np.arange(5,17).reshape((3,4))
print(a)
b=a[2:,1:3].copy()
print(b)
b[0][1]=200
print(b)
print(a)


[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[14 15]]
[[ 14 200]]
[[  5   6   7   8]
 [  9  10  11  12]
 [ 13  14 200  16]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[14 15]]
[[ 14 200]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


JOINING TOW ARRAYS
1>>np.hstack()
2>>np.vstack()
3>>np.block()

np.hstack()

In [48]:
a=np.arange(6,12).reshape(2,3)
print(a)
a2=np.arange(8).reshape(2,4)
print(a2)
a3=np.hstack((a,a2))
print(a3)

[[ 6  7  8]
 [ 9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 6  7  8  0  1  2  3]
 [ 9 10 11  4  5  6  7]]


np.vstack()

In [55]:
a=np.arange(6,12).reshape(2,3)
print(a)
a2=np.arange(12).reshape(3,3)
print(a2)
a3=np.vstack([a,a2])
print(a3)

[[ 6  7  8]
 [ 9 10 11]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 6  7  8]
 [ 9 10 11]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [56]:
#split()
a=np.arange(15)
b=np.split(a,5)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11]), array([12, 13, 14])]


In [57]:
a=np.arange(34,49)
b=np.split(a,[3,5,10,13])  #List of subarrays
print(a)
print(b)
for arr in b:
    print(arr.sum())

[34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[array([34, 35, 36]), array([37, 38]), array([39, 40, 41, 42, 43]), array([44, 45, 46]), array([47, 48])]
105
75
205
135
95


In [2]:
import numpy as np

In [9]:
a=np.array([12,56,23,11])
print(a)
print(a.argsort())
################################
a=np.array([12,56,23,11])
print(a)
print(a.argmin())
################################
a=np.array([12,56,23,11])
print(a)
print(a.argmax())
################################
a=np.array([12,56,23,11])
print(a)
a.sort()
print(a)


[12 56 23 11]
[3 0 2 1]
[12 56 23 11]
3
[12 56 23 11]
1
[12 56 23 11]
[11 12 23 56]
[[12 56 23 11]
 [ 7  3  1 61]]
61
[12 56 23 61]
[56 61]


In [12]:
import numpy as np
a=np.array([[12,56,23,11],[7,3,1,61]])
print(a)
print(a.max())
print(a.max(axis=0))  #column wise 
print(a.max(axis=1))  #row wise

[[12 56 23 11]
 [ 7  3  1 61]]
61
[12 56 23 61]
[56 61]


ARATHMATIC OPRATION IN ARRAY


In [13]:
a=np.array([[1,6,7],[2,5,3],[1,5,8]])
print(a)
print(a+5)
print(a-3)
print(a*4)
print(a/5)

[[1 6 7]
 [2 5 3]
 [1 5 8]]
[[ 6 11 12]
 [ 7 10  8]
 [ 6 10 13]]
[[-2  3  4]
 [-1  2  0]
 [-2  2  5]]
[[ 4 24 28]
 [ 8 20 12]
 [ 4 20 32]]
[[0.2 1.2 1.4]
 [0.4 1.  0.6]
 [0.2 1.  1.6]]


In [14]:
#transpose of a matrix
a=np.arange(6).reshape(3,2)
print(a)
print(a.T)

[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]


In [19]:
a=np.arange(6).reshape(2,3)
a2=np.array([[1,2],[2,1],[-1,2]])
print(a)
print(a2)
# a3=np.dot(a,a2)
#or use
a3=a@a2
print(a3)

[[0 1 2]
 [3 4 5]]
[[ 1  2]
 [ 2  1]
 [-1  2]]
[[ 0  5]
 [ 6 20]]


In [21]:
#determinent of the matrix
#linalg:Linear algebra function
a=np.array([[2,3],[4,1]])
print(a)
print(int(np.linalg.det(a)))

[[2 3]
 [4 1]]
-10


In [25]:
import pandas as pd

In [26]:
!pip install pandas

In [1]:
import pandas as pd